### ISSUE TITLE
Why don't use min.js?

### ISSUE THREAD

**Issue by antonmarin** [fedemotta/yii2-gridstack#3]
I think we should use min.js for production. Ex:
```
$this->js = YII_ENV_PROD ? gridstack.min.js : gridstack.js;
```

**Comment by fedemotta** [comment]
Hi,
Thank you for your comment!

What happens if someone it is not using that constant? I think we should use another approach to use the minify version.

Feel free to send a pull request if you want.

Cheers

**Comment by antonmarin** [comment]
As we talk about Yii2 extension, this constant will always be used as it init at BaseYii::32

**Comment by antonmarin** [comment]
any updates?

**Comment by fedemotta** [comment]
Hi @antonmarin,
I am busy right now and I could not dedicate to much time to this project.

Anyway, send me the pull request and I will merge it.

Cheers
